//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ciceksepeti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Satis()
        {
            this.sepet = new HashSet<sepet>();
        }
    
        public int satis_id { get; set; }
        public string satis_adres { get; set; }
        public Nullable<int> kullanici_id { get; set; }
        public Nullable<long> kart_hesapno { get; set; }
        public Nullable<int> kart_CVCkod { get; set; }
        public string kart_adsoyad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sepet> sepet { get; set; }
    }
}
