//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ciceksepeti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sepet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sepet()
        {
            this.sepeturunliste = new HashSet<sepeturunliste>();
        }
    
        public int sepet_id { get; set; }
        public Nullable<int> kullanıcı_id { get; set; }
        public Nullable<int> satis_id { get; set; }
    
        public virtual kullanici kullanici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sepeturunliste> sepeturunliste { get; set; }
        public virtual Satis Satis { get; set; }
    }
}
