//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ciceksepeti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sepeturunliste
    {
        public int sul_id { get; set; }
        public Nullable<int> sepet_id { get; set; }
        public Nullable<int> urun_id { get; set; }
        public Nullable<int> adet { get; set; }
    
        public virtual sepet sepet { get; set; }
        public virtual urunler urunler { get; set; }
    }
}
